**CLEANING A MESSY DATA SET**

In [442]:
import pandas as pd
import numpy as np


df = pd.read_csv("/content/messy_ecommerce_dataset.csv")

**>> DATA OVERVIEW**

In [443]:
# Display first rows of the dataset
df.head()

,order_id,customer_name,email,country,order_date,revenue,age
0,1001,Mario Rossi,mario@gmail.com,Italy,12/01/2025,€120,32.0
1,1002,maria rossi,MARIA@gmail.com,ITALIA,2025-01-13,89€,NaN
2,1003,Luca Bianchi,luca@gmail,Italia,Jan 14 2025,one hundred,29.0
3,1003,Luca Bianchi,luca@gmail,Italia,Jan 14 2025,one hundred,29.0
4,1004,Anna Verdi,anna@gmail.com,italy,14-01-25,€250,150.0

In [444]:
# Shape of the dataset (rows, columns)
df.shape

(10, 7)

In [445]:
# Overview of the dataset structure (columns, data types, non-null values).
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       10 non-null     int64
 1   customer_name  9 non-null      object
 2   email          10 non-null     object
 3   country        10 non-null     object
 4   order_date     9 non-null      object
 5   revenue        10 non-null     object
 6   age            8 non-null      float64
dtypes: float64(1), int64(1), object(5)
memory usage: 692.0+ bytes

In [446]:
# Summary statistics for numerical columns.
df.describe()

         order_id         age
count    10.00000    8.000000
mean   1004.80000   42.125000
std       2.65832   45.652218
min    1001.00000   -5.000000
25%    1003.00000   28.500000
50%    1004.50000   30.500000
75%    1006.75000   36.250000
max    1009.00000  150.000000

In [447]:
# Count of missing values per column.
df.isnull().sum()

order_id         0
customer_name    1
email            0
country          0
order_date       1
revenue          0
age              2
dtype: int64

**>> DATA CLEANING**

1st column : order_id

In [448]:
# Check for duplicated in column "order_id"
duplicate = df["order_id"].duplicated().sum()
print(f"The number of duplicated values is : {duplicate}")

The number of duplicated values is : 1

In [449]:
# Inspect duplicated order_id to determine if rows are identical or contain inconsistencies
df[df["order_id"].duplicated(keep=False)]

   order_id customer_name       email country   order_date      revenue   age
2      1003  Luca Bianchi  luca@gmail  Italia  Jan 14 2025  one hundred  29.0
3      1003  Luca Bianchi  luca@gmail  Italia  Jan 14 2025  one hundred  29.0

In [450]:
# Remove duplicate rows based on order_id
df = df.drop_duplicates(subset="order_id")

# Check again for duplicated values
duplicate = df["order_id"].duplicated().sum()
print(f"The number of duplicated values is : {duplicate}")

The number of duplicated values is : 0

2nd column : customer_name

In [451]:
# Check missing values in customer_name
missing_values = df["customer_name"].isnull().sum()
print(f"The number of missing values is : {missing_values}")

The number of missing values is : 1

In [452]:
print(df)

df["customer_name"].value_counts()

# Standardize customer_name formatting
df["customer_name"] = df["customer_name"].str.strip().str.title()

print(df)

   order_id customer_name             email country   order_date      revenue  \
0      1001   Mario Rossi   mario@gmail.com   Italy   12/01/2025         €120
1      1002   maria rossi   MARIA@gmail.com  ITALIA   2025-01-13          89€
2      1003  Luca Bianchi        luca@gmail  Italia  Jan 14 2025  one hundred
4      1004    Anna Verdi    anna@gmail.com   italy     14-01-25         €250
5      1005           NaN   paolo@gmail.com      IT      missing          €75
6      1006   Giulia Neri  giulia@gmail.com  Italy    2025/01/15         €200
7      1007     Marco Blu   marco@gmail.com  Italya  15 Jan 2025         300€
8      1008   Sara Gialli        sara@gmail   ITALY   2025.01.16         €180
9      1009    Paolo Rosa   paolo@gmail.com      IT          NaN          €90

     age
0   32.0
1    NaN
2   29.0
4  150.0
5   -5.0
6   27.0
7   40.0
8    NaN
9   35.0
   order_id customer_name             email country   order_date      revenue  \
0      1001   Mario Rossi   mario@gmail.com   Italy   12/01/2025         €120
1      1002   Maria Rossi   MARIA@gmail.com  ITALIA   2025-01-13          89€
2      1003  Luca Bianchi        luca@gmail  Italia  Jan 14 2025  one hundred
4      1004    Anna Verdi    anna@gmail.com   italy     14-01-25         €250
5      1005           NaN   paolo@gmail.com      IT      missing          €75
6      1006   Giulia Neri  giulia@gmail.com  Italy    2025/01/15         €200
7      1007     Marco Blu   marco@gmail.com  Italya  15 Jan 2025         300€
8      1008   Sara Gialli        sara@gmail   ITALY   2025.01.16         €180
9      1009    Paolo Rosa   paolo@gmail.com      IT          NaN          €90

     age
0   32.0
1    NaN
2   29.0
4  150.0
5   -5.0
6   27.0
7   40.0
8    NaN
9   35.0

In [453]:
# SReplace missing names (NaN) with placeholder ("Unknown")
df["customer_name"] = df["customer_name"].fillna("Unknown")
print(df)

df = df[df["customer_name"] != "Unknown"]
print(df)

   order_id customer_name             email country   order_date      revenue  \
0      1001   Mario Rossi   mario@gmail.com   Italy   12/01/2025         €120
1      1002   Maria Rossi   MARIA@gmail.com  ITALIA   2025-01-13          89€
2      1003  Luca Bianchi        luca@gmail  Italia  Jan 14 2025  one hundred
4      1004    Anna Verdi    anna@gmail.com   italy     14-01-25         €250
5      1005       Unknown   paolo@gmail.com      IT      missing          €75
6      1006   Giulia Neri  giulia@gmail.com  Italy    2025/01/15         €200
7      1007     Marco Blu   marco@gmail.com  Italya  15 Jan 2025         300€
8      1008   Sara Gialli        sara@gmail   ITALY   2025.01.16         €180
9      1009    Paolo Rosa   paolo@gmail.com      IT          NaN          €90

     age
0   32.0
1    NaN
2   29.0
4  150.0
5   -5.0
6   27.0
7   40.0
8    NaN
9   35.0
   order_id customer_name             email country   order_date      revenue  \
0      1001   Mario Rossi   mario@gmail.com   Italy   12/01/2025         €120
1      1002   Maria Rossi   MARIA@gmail.com  ITALIA   2025-01-13          89€
2      1003  Luca Bianchi        luca@gmail  Italia  Jan 14 2025  one hundred
4      1004    Anna Verdi    anna@gmail.com   italy     14-01-25         €250
6      1006   Giulia Neri  giulia@gmail.com  Italy    2025/01/15         €200
7      1007     Marco Blu   marco@gmail.com  Italya  15 Jan 2025         300€
8      1008   Sara Gialli        sara@gmail   ITALY   2025.01.16         €180
9      1009    Paolo Rosa   paolo@gmail.com      IT          NaN          €90

     age
0   32.0
1    NaN
2   29.0
4  150.0
6   27.0
7   40.0
8    NaN
9   35.0

3rd column : email

In [454]:
# Check frequency emails
df["email"].value_counts()

email
mario@gmail.com     1
MARIA@gmail.com     1
luca@gmail          1
anna@gmail.com      1
giulia@gmail.com    1
marco@gmail.com     1
sara@gmail          1
paolo@gmail.com     1
Name: count, dtype: int64

In [455]:
# Check for NOT valid emails (missing '@' or '.')
invalid_emails = df[
    ~df["email"].str.contains("@") |
    ~df["email"].str.contains(r"\.")
]

print(invalid_emails)

   order_id customer_name       email country   order_date      revenue   age
2      1003  Luca Bianchi  luca@gmail  Italia  Jan 14 2025  one hundred  29.0
8      1008   Sara Gialli  sara@gmail   ITALY   2025.01.16         €180   NaN

In [456]:
# Set invalid email formats to NaN to avoid introducing incorrect information
df.loc[
    ~(
        df["email"].str.contains("@") &
        df["email"].str.contains(r"\.")
    ),
    "email"
] = np.nan

print(df["email"])

0     mario@gmail.com
1     MARIA@gmail.com
2                 NaN
4      anna@gmail.com
6    giulia@gmail.com
7     marco@gmail.com
8                 NaN
9     paolo@gmail.com
Name: email, dtype: object

In [457]:
df["email"] = df["email"].str.lower()
df

,order_id,customer_name,email,country,order_date,revenue,age
0,1001,Mario Rossi,mario@gmail.com,Italy,12/01/2025,€120,32.0
1,1002,Maria Rossi,maria@gmail.com,ITALIA,2025-01-13,89€,NaN
2,1003,Luca Bianchi,NaN,Italia,Jan 14 2025,one hundred,29.0
4,1004,Anna Verdi,anna@gmail.com,italy,14-01-25,€250,150.0
6,1006,Giulia Neri,giulia@gmail.com,Italy,2025/01/15,€200,27.0
7,1007,Marco Blu,marco@gmail.com,Italya,15 Jan 2025,300€,40.0
8,1008,Sara Gialli,NaN,ITALY,2025.01.16,€180,NaN
9,1009,Paolo Rosa,paolo@gmail.com,IT,NaN,€90,35.0

4th column : country

In [458]:
# Check unique values in country column
df["country"].value_counts()

country
Italy     1
ITALIA    1
Italia    1
italy     1
Italy     1
Italya    1
ITALY     1
IT        1
Name: count, dtype: int64

In [459]:
# Normalize text (lowercase + remove extra spaces)
df["country"] = df["country"].str.lower().str.strip()

df["country"]

0     italy
1    italia
2    italia
4     italy
6     italy
7    italya
8     italy
9        it
Name: country, dtype: object

In [460]:
# Map all variations to 'italy'

df["country"] = df["country"].replace({
    "italia": "italy",
    "it" : "italy",
    "italya" : "italy",
}
)

df["country"]

0    italy
1    italy
2    italy
4    italy
6    italy
7    italy
8    italy
9    italy
Name: country, dtype: object

In [461]:
# Standardize final format (capitalize)
df["country"] = df["country"].str.title()

df["country"].value_counts()

country
Italy    8
Name: count, dtype: int64

5th column : order_date

In [462]:
# Check raw values of order_date
df["order_date"]

0     12/01/2025
1     2025-01-13
2    Jan 14 2025
4       14-01-25
6     2025/01/15
7    15 Jan 2025
8     2025.01.16
9            NaN
Name: order_date, dtype: object

In [463]:
# Normalize date separators
df["order_date"] = df["order_date"].str.replace("/", "-", regex=False)
df["order_date"] = df["order_date"].str.replace(".", "-", regex=False)
df["order_date"]

0     12-01-2025
1     2025-01-13
2    Jan 14 2025
4       14-01-25
6     2025-01-15
7    15 Jan 2025
8     2025-01-16
9            NaN
Name: order_date, dtype: object

In [464]:
# Due to inconsistent date formats, a new cleaned column "order_date_clean" is created with manually standardized values.

df["order_date_clean"] = [
    "12-01-2025",
    "13-01-2025",
    "14-01-2025",
    "14-01-2025",
    "15-01-2025",
    "15-01-2025",
    "16-01-2025",
    None
]

df["order_date_clean"]

0    12-01-2025
1    13-01-2025
2    14-01-2025
4    14-01-2025
6    15-01-2025
7    15-01-2025
8    16-01-2025
9          None
Name: order_date_clean, dtype: object

In [465]:
df["order_date_clean"] = pd.to_datetime(
    df["order_date_clean"],
    dayfirst=True
)


df["order_date_clean"]
df

,order_id,customer_name,email,country,order_date,revenue,age,order_date_clean
0,1001,Mario Rossi,mario@gmail.com,Italy,12-01-2025,€120,32.0,2025-01-12
1,1002,Maria Rossi,maria@gmail.com,Italy,2025-01-13,89€,NaN,2025-01-13
2,1003,Luca Bianchi,NaN,Italy,Jan 14 2025,one hundred,29.0,2025-01-14
4,1004,Anna Verdi,anna@gmail.com,Italy,14-01-25,€250,150.0,2025-01-14
6,1006,Giulia Neri,giulia@gmail.com,Italy,2025-01-15,€200,27.0,2025-01-15
7,1007,Marco Blu,marco@gmail.com,Italy,15 Jan 2025,300€,40.0,2025-01-15
8,1008,Sara Gialli,NaN,Italy,2025-01-16,€180,NaN,2025-01-16
9,1009,Paolo Rosa,paolo@gmail.com,Italy,NaN,€90,35.0,NaT

In [466]:
# Replace original column
df["order_date"] = df["order_date_clean"]

# Drop helper column
df = df.drop(columns=["order_date_clean"])

6th column : revenue

In [467]:
df["revenue"]

0           €120
1            89€
2    one hundred
4           €250
6           €200
7           300€
8           €180
9            €90
Name: revenue, dtype: object

In [468]:
df["revenue"] = df["revenue"].str.replace("€", "", regex=False)
df["revenue"]

0            120
1             89
2    one hundred
4            250
6            200
7            300
8            180
9             90
Name: revenue, dtype: object

In [469]:
# Convert to numeric (invalid values → NaN)
df["revenue"] = pd.to_numeric(df["revenue"], errors="coerce")
print(df["revenue"])

media = df["revenue"].mean()
print(media)

0    120.0
1     89.0
2      NaN
4    250.0
6    200.0
7    300.0
8    180.0
9     90.0
Name: revenue, dtype: float64
175.57142857142858

In [470]:
#Rename column "revenue" with "revenue_Euro(€)"
df.rename(columns={"revenue": "revenue_Euro(€)"}, inplace=True)
df

,order_id,customer_name,email,country,order_date,revenue_Euro(€),age
0,1001,Mario Rossi,mario@gmail.com,Italy,2025-01-12,120.0,32.0
1,1002,Maria Rossi,maria@gmail.com,Italy,2025-01-13,89.0,NaN
2,1003,Luca Bianchi,NaN,Italy,2025-01-14,NaN,29.0
4,1004,Anna Verdi,anna@gmail.com,Italy,2025-01-14,250.0,150.0
6,1006,Giulia Neri,giulia@gmail.com,Italy,2025-01-15,200.0,27.0
7,1007,Marco Blu,marco@gmail.com,Italy,2025-01-15,300.0,40.0
8,1008,Sara Gialli,NaN,Italy,2025-01-16,180.0,NaN
9,1009,Paolo Rosa,paolo@gmail.com,Italy,NaT,90.0,35.0

7ty column : age

In [471]:
df["age"]

0     32.0
1      NaN
2     29.0
4    150.0
6     27.0
7     40.0
8      NaN
9     35.0
Name: age, dtype: float64

In [472]:
df.loc[(df["age"] < 0) | (df["age"] > 100), "age"] = None
df["age"]

df["age"] = df["age"].astype("Int64")
df["age"]

0      32
1    <NA>
2      29
4    <NA>
6      27
7      40
8    <NA>
9      35
Name: age, dtype: Int64

**>> FINAL RESULT**

In [473]:
df.reset_index(drop=True, inplace=True)
df

,order_id,customer_name,email,country,order_date,revenue_Euro(€),age
0,1001,Mario Rossi,mario@gmail.com,Italy,2025-01-12,120.0,32
1,1002,Maria Rossi,maria@gmail.com,Italy,2025-01-13,89.0,<NA>
2,1003,Luca Bianchi,NaN,Italy,2025-01-14,NaN,29
3,1004,Anna Verdi,anna@gmail.com,Italy,2025-01-14,250.0,<NA>
4,1006,Giulia Neri,giulia@gmail.com,Italy,2025-01-15,200.0,27
5,1007,Marco Blu,marco@gmail.com,Italy,2025-01-15,300.0,40
6,1008,Sara Gialli,NaN,Italy,2025-01-16,180.0,<NA>
7,1009,Paolo Rosa,paolo@gmail.com,Italy,NaT,90.0,35

# **# Final cleaned dataset ready for analysis**

In [474]:
# Exporting the 'cleaned' version of the dataset
df.to_csv("cleaned_ecommerce_dataset.csv", index=False)